USE KaraokeDB;

INSERT INTO User(name, email) VALUES
('Alice', 'alice@gmail.com'),
('Bobby', 'bobby@gmail.com'),
('Charles', 'charles@gmail.com'),
('David', 'david@gmail.com'),
('Eve', 'eve@gmail.com'),
('Wemby', 'Wemby@gmail.com'),
('Grace', 'grace@gmail.com'),
('Hank', 'hank@gmail.com'),
('Ian', 'ian@gmail.com'),
('Jacky', 'jacky@gmail.com');

INSERT INTO Artist(artist_name) VALUES
('The Weeknd'),
('Mark Ronson'),
('Bruno Mars'),
('Ed Sheeran'),
('Adele'),
('Queen'),
('Lady Gaga'),
('Bradley Cooper'),
('Lil Nas X'),
('Billy Ray Cyrus'),
('Luis Fonsi'),
('Daddy Yankee'),
('Pharrell Williams'),
('BTS'),
('Billie Eilish'),
('Taylor Swift'),
('Bee Gees'),
('Harry Styles'),
('Dua Lipa'),
('Post Malone'),
('Shakira'),
('John Legend'),
('Carly Rae Jepsen'),
('Imagine Dragons'),
('Shawn Mendes'),
('Camila Cabello'),
('Neil Diamond'),
('Journey');


INSERT INTO Song (title, genre, karaoke_file, artist_id) VALUES
('Blinding Lights', 'Pop', 'blinding_lights.kar', 1),
('Uptown Funk', 'Funk', 'uptown_funk.kar', 2),
('Shape of You', 'Pop', 'shape_of_you.kar', 3),
('Rolling in the Deep', 'Pop', 'rolling_in_the_deep.kar', 4),
('Bohemian Rhapsody', 'Rock', 'bohemian_rhapsody.kar', 5),
('Shallow', 'Pop', 'shallow.kar', 6),
('Old Town Road', 'Country', 'old_town_road.kar', 7),
('Someone Like You', 'Pop', 'someone_like_you.kar', 4),
('Despacito', 'Reggaeton', 'despacito.kar', 8),
('Happy', 'Pop', 'happy.kar', 9),
('Dynamite', 'Pop', 'dynamite.kar', 10),
('Bad Guy', 'Pop', 'bad_guy.kar', 11),
('Thinking Out Loud', 'Pop', 'thinking_out_loud.kar', 3),
('Shake It Off', 'Pop', 'shake_it_off.kar', 12),
('Hello', 'Pop', 'hello.kar', 4),
('Stayin Alive', 'Disco', 'stayin_alive.kar', 13),
('Watermelon Sugar', 'Pop', 'watermelon_sugar.kar', 14),
('Levitating', 'Pop', 'levitating.kar', 15),
('Sunflower', 'Pop', 'sunflower.kar', 16),
('Waka Waka', 'Pop', 'waka_waka.kar', 17),
('All of Me', 'Pop', 'all_of_me.kar', 18),
('Call Me Maybe', 'Pop', 'call_me_maybe.kar', 19),
('Believer', 'Rock', 'believer.kar', 20),
('Señorita', 'Pop', 'senorita.kar', 21),
('Radioactive', 'Rock', 'radioactive.kar', 20),
('Closer', 'Pop', 'closer.kar', 22),
('Havana', 'Pop', 'havana.kar', 23),
('We Will Rock You', 'Rock', 'we_will_rock_you.kar', 5),
('Sweet Caroline', 'Pop', 'sweet_caroline.kar', 24),
('Don''t Stop Believin''', 'Rock', 'dont_stop_believin.kar', 25);

INSERT INTO Contributor(name, contributor_type) VALUES
('Max Martin', 'Producer'),
('Pharrell Williams', 'Producer'),
('Ed Sheeran', 'Songwriter'),
('Ryan Tedder', 'Songwriter'),
('David Guetta', 'Producer'),
('Sia', 'Songwriter');

INSERT INTO SongArtist (song_id, artist_id) VALUES
(1, 1),
(2, 2),
(2, 3),
(3, 4),
(4, 5),
(5, 6),
(6, 7),
(6, 8),
(7, 9),
(7, 10),
(8, 11),
(9, 12),
(9, 13),
(10, 14),
(11, 15),
(12, 16),
(13, 17),
(14, 18),
(15, 19),
(16, 20),
(17, 21),
(18, 22),
(19, 23),
(20, 24),
(21, 25),
(22, 26);

INSERT INTO SongContributor (song_id, contributor_id) VALUES
(1, 1),
(2, 2),
(2, 3),
(3, 4),
(4, 5),
(5, 6);
INSERT INTO Queue (q_type, user_id, song_id) VALUES
(1, 1, 1),
(1, 2, 2),
(2, 3, 3),
(1, 4, 4),
(2, 5, 5),
(1, 6, 6),
(2, 7, 7),
(1, 8, 8),
(1, 9, 9),
(2, 10, 10);
